# Generated by Django 6.0.7 on 2026-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_vedette',
            field=models.BooleanField(default=False, verbose_name='Produit vedette'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel'),
        ),
    ]
